### ISSUE TITLE
DUVIDAS

### ISSUE THREAD

**Issue by CampeonatoJJJE** [tlbdmecanica/Mecanica#10]
Olá pessoal, vocês estão tendo alguma duvida? Caso houver estamos de prontidão! Obrigado, beijo no coração. <3

**Comment by CartinhaSquadETEC** [comment]
???
@CampeonatoJJJE

**Comment by CampeonatoJJJE** [comment]
ops.. foi mau kkkkk

**Comment by bmarchete** [comment]
Essa Issue não faz nenhum sentido. Podem fechá-la
