### ISSUE TITLE
Erro grave na modelagem!

### ISSUE THREAD

**Issue by bmarchete** [tlbdmecanica/Mecanica#11]
Pessoal, observando aqui, uma ordem de serviço só pode possuir um produto? E os serviços prestados na ordem de serviços, onde estão?

**Comment by tlbdmecanica** [comment]
Bom, para a simplificação do nosso projeto, decidimos não criarmos outra tabela para os produtos vendidos nas ordens de serviço e na questão dos serviços prestados, cada funcionário é especializado em uma área no conserto de carros.

**Comment by tlbdmecanica** [comment]
Estamos refazendo o banco e colocaremos em uma pasta no nosso repositório.
